import blockContent from './blockContent'
import noticias from './noticias'
import publicaciones from './publicaciones'
import equipo from './equipo'
import proyectos from './proyectos'
import ejes from './ejes'
import curso from './curso'
import proyectoPrincipal from './proyectoPrincipal'
import quienesSomos from './quienesSomos'
import practicantes from './practicantes'   
import descripcionInicio from './descripcionInicio'
import equipamiento from './equipamiento'
import tesisypracticantes from './tesisypracticantes'
import divulgacionCIentifica from './divulgacionCIentifica'
import caminataSonora from './caminataSonora'
import footer from './footer'
import colaboradores from './colaboradores'
import colaboradoresAsociados from './colaboradoresAsociados'

export const schemaTypes = [noticias, blockContent, publicaciones, proyectos, equipo, ejes, curso, proyectoPrincipal, quienesSomos, practicantes, descripcionInicio, equipamiento, tesisypracticantes, divulgacionCIentifica, caminataSonora, footer, colaboradores, colaboradoresAsociados]